image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --pull -t $DOCKER_IMAGE .

push:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main
