image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: docker.io/xaqani90/dockrepo:latest

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

push:
  stage: push
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main

